version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  phantomjs:
    image: wernight/phantomjs
    container_name: phantomjs
    restart: always
    ports:
      - "8910:8910"
    command: "phantomjs --webdriver=8910 --ignore-ssl-errors=true --ssl-protocol=any"
